### ISSUE TITLE
Write introduction

### ISSUE THREAD

**Issue by JJ** [JJ/2021-cec-deep-g-prop#4]
While we can re-use @lulivi 's introduction, we'll probably have to condense it at the same time we translate it.

**Comment by pacastillo** [comment]
Instead of the last sentence:
  " This does not imply that we are actually doing deep machine learning at large; but
we are using (potentially) deep neural nets (with more than one
layer), and a training method that is suitable for deep neural nets,
leaving the possibility of using deep neural nets open for the future. "

I'd say something like:
   " This paper presents a first approach to perform deep neural networks evolution (evolution of MLPs with several layers), providing results of the evolution of networks with two layers, and demonstrating that the method can be applied to the evolution of networks with a high number of layers. "

**Comment by pacastillo** [comment]
I include that in the source code, but I leave it commented.
